#!/usr/bin/env bash

# 1. search for text in files using ripgrep
# 2. interactively restart ripgrep w/ reload action --> look at using parallels with fd/rg via Julian's dotfiles!
# 3. Open the file in nvim
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case"
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
  fzf --ansi \
      --disabled --query "$INITIAL_QUERY" \
      --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
      --delimiter : \
      --preview 'bat --color=always {1} --highlight-line {2}' \
      --preview-window right
)
[ -n "${selected[0]}"] && nvim "${selected[0]}:${selected[1]}"
# 'up,60%,border-down,+{2}+3/3,~3'
