#!/bin/bash

github() {
  if [ $# -eq 0 ]; then
    open /Applications/Safari.app https://github.com/eo1989/
  elif [ $# -eq 1 ]; then
    open /Applications/Safari.app https://github.com/eo1989/"$1"
  elif [ $# -eq 2 ]; then
    open /Applications/Safari.app https://github.com/"$1"/"$2"
  fi
}
