#!/usr/bin/env bash

trunc_field() {
  local STR=$1
  local CHARS=$2
  local EXP=""
  local COUNT=0
  while [ $COUNT -lt $CHARS ]; do
    EXP="$EXP."
    COUNT=$(expr $COUNT + 1)
  done
  echo $STR | sed "s/^\($EXP\).*$/\1/"
}

printf "%10s | something\n" "$(trunc_field "$TEXT" 20)"
